/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers, EventFilter, Signer, BigNumber, BigNumberish, PopulatedTransaction } from 'ethers'
import {
    Contract,
    ContractTransaction,
    Overrides,
    PayableOverrides,
    CallOverrides,
} from '@ethersproject/contracts'
import { BytesLike } from '@ethersproject/bytes'
import { Listener, Provider } from '@ethersproject/providers'
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi'
import { TypedEventFilter, TypedEvent, TypedListener } from './commons'

interface PrintingPressAbiInterface extends ethers.utils.Interface {
    functions: {
        'EulerBeats()': FunctionFragment
        'addScriptEB(string)': FunctionFragment
        'burnEnabled()': FunctionFragment
        'burnPrint(uint256,uint256)': FunctionFragment
        'ensureEulerBeatsSeedOwner(uint256,address)': FunctionFragment
        'getSeedIds()': FunctionFragment
        'mintPrint(uint256,address)': FunctionFragment
        'onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)': FunctionFragment
        'onERC1155Received(address,address,uint256,uint256,bytes)': FunctionFragment
        'owner()': FunctionFragment
        'printEnabled()': FunctionFragment
        'renounceOwnership()': FunctionFragment
        'resetScriptCountEB()': FunctionFragment
        'seedToPrintId(uint256)': FunctionFragment
        'setBurnEnabled(bool)': FunctionFragment
        'setEnabledEB(bool)': FunctionFragment
        'setLockedEB(bool)': FunctionFragment
        'setPrintEnabled(bool)': FunctionFragment
        'setURIEB(string)': FunctionFragment
        'supportsInterface(bytes4)': FunctionFragment
        'transferOwnership(address)': FunctionFragment
        'transferOwnershipEB(address)': FunctionFragment
        'updateScriptEB(string,uint256)': FunctionFragment
        'withdraw()': FunctionFragment
        'withdrawEB()': FunctionFragment
    }

    encodeFunctionData(functionFragment: 'EulerBeats', values?: undefined): string
    encodeFunctionData(functionFragment: 'addScriptEB', values: [string]): string
    encodeFunctionData(functionFragment: 'burnEnabled', values?: undefined): string
    encodeFunctionData(functionFragment: 'burnPrint', values: [BigNumberish, BigNumberish]): string
    encodeFunctionData(
        functionFragment: 'ensureEulerBeatsSeedOwner',
        values: [BigNumberish, string]
    ): string
    encodeFunctionData(functionFragment: 'getSeedIds', values?: undefined): string
    encodeFunctionData(functionFragment: 'mintPrint', values: [BigNumberish, string]): string
    encodeFunctionData(
        functionFragment: 'onERC1155BatchReceived',
        values: [string, string, BigNumberish[], BigNumberish[], BytesLike]
    ): string
    encodeFunctionData(
        functionFragment: 'onERC1155Received',
        values: [string, string, BigNumberish, BigNumberish, BytesLike]
    ): string
    encodeFunctionData(functionFragment: 'owner', values?: undefined): string
    encodeFunctionData(functionFragment: 'printEnabled', values?: undefined): string
    encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string
    encodeFunctionData(functionFragment: 'resetScriptCountEB', values?: undefined): string
    encodeFunctionData(functionFragment: 'seedToPrintId', values: [BigNumberish]): string
    encodeFunctionData(functionFragment: 'setBurnEnabled', values: [boolean]): string
    encodeFunctionData(functionFragment: 'setEnabledEB', values: [boolean]): string
    encodeFunctionData(functionFragment: 'setLockedEB', values: [boolean]): string
    encodeFunctionData(functionFragment: 'setPrintEnabled', values: [boolean]): string
    encodeFunctionData(functionFragment: 'setURIEB', values: [string]): string
    encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string
    encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string
    encodeFunctionData(functionFragment: 'transferOwnershipEB', values: [string]): string
    encodeFunctionData(functionFragment: 'updateScriptEB', values: [string, BigNumberish]): string
    encodeFunctionData(functionFragment: 'withdraw', values?: undefined): string
    encodeFunctionData(functionFragment: 'withdrawEB', values?: undefined): string

    decodeFunctionResult(functionFragment: 'EulerBeats', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'addScriptEB', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'burnEnabled', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'burnPrint', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'ensureEulerBeatsSeedOwner', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'getSeedIds', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'mintPrint', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'onERC1155BatchReceived', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'onERC1155Received', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'printEnabled', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'resetScriptCountEB', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'seedToPrintId', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'setBurnEnabled', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'setEnabledEB', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'setLockedEB', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'setPrintEnabled', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'setURIEB', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'transferOwnershipEB', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'updateScriptEB', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'withdrawEB', data: BytesLike): Result

    events: {
        'OwnershipTransferred(address,address)': EventFragment
    }

    getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
}

export class PrintingPressAbi extends Contract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    listeners<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
    ): Array<TypedListener<EventArgsArray, EventArgsObject>>
    off<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
        listener: TypedListener<EventArgsArray, EventArgsObject>
    ): this
    on<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
        listener: TypedListener<EventArgsArray, EventArgsObject>
    ): this
    once<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
        listener: TypedListener<EventArgsArray, EventArgsObject>
    ): this
    removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
        listener: TypedListener<EventArgsArray, EventArgsObject>
    ): this
    removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
        eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
    ): this

    listeners(eventName?: string): Array<Listener>
    off(eventName: string, listener: Listener): this
    on(eventName: string, listener: Listener): this
    once(eventName: string, listener: Listener): this
    removeListener(eventName: string, listener: Listener): this
    removeAllListeners(eventName?: string): this

    queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
        event: TypedEventFilter<EventArgsArray, EventArgsObject>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>

    interface: PrintingPressAbiInterface

    functions: {
        EulerBeats(overrides?: CallOverrides): Promise<[string]>

        'EulerBeats()'(overrides?: CallOverrides): Promise<[string]>

        addScriptEB(_script: string, overrides?: Overrides): Promise<ContractTransaction>

        'addScriptEB(string)'(_script: string, overrides?: Overrides): Promise<ContractTransaction>

        burnEnabled(overrides?: CallOverrides): Promise<[boolean]>

        'burnEnabled()'(overrides?: CallOverrides): Promise<[boolean]>

        burnPrint(
            seed: BigNumberish,
            minimumSupply: BigNumberish,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        'burnPrint(uint256,uint256)'(
            seed: BigNumberish,
            minimumSupply: BigNumberish,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        ensureEulerBeatsSeedOwner(
            seed: BigNumberish,
            _owner: string,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        'ensureEulerBeatsSeedOwner(uint256,address)'(
            seed: BigNumberish,
            _owner: string,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        getSeedIds(
            overrides?: CallOverrides
        ): Promise<
            [
                [
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber
                ]
            ] & {
                seedIds: [
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber
                ]
            }
        >

        'getSeedIds()'(
            overrides?: CallOverrides
        ): Promise<
            [
                [
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber
                ]
            ] & {
                seedIds: [
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber,
                    BigNumber
                ]
            }
        >

        mintPrint(
            seed: BigNumberish,
            _owner: string,
            overrides?: PayableOverrides
        ): Promise<ContractTransaction>

        'mintPrint(uint256,address)'(
            seed: BigNumberish,
            _owner: string,
            overrides?: PayableOverrides
        ): Promise<ContractTransaction>

        onERC1155BatchReceived(
            arg0: string,
            arg1: string,
            arg2: BigNumberish[],
            arg3: BigNumberish[],
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        'onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)'(
            arg0: string,
            arg1: string,
            arg2: BigNumberish[],
            arg3: BigNumberish[],
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        onERC1155Received(
            arg0: string,
            arg1: string,
            arg2: BigNumberish,
            arg3: BigNumberish,
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        'onERC1155Received(address,address,uint256,uint256,bytes)'(
            arg0: string,
            arg1: string,
            arg2: BigNumberish,
            arg3: BigNumberish,
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        owner(overrides?: CallOverrides): Promise<[string]>

        'owner()'(overrides?: CallOverrides): Promise<[string]>

        printEnabled(overrides?: CallOverrides): Promise<[boolean]>

        'printEnabled()'(overrides?: CallOverrides): Promise<[boolean]>

        renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>

        'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>

        resetScriptCountEB(overrides?: Overrides): Promise<ContractTransaction>

        'resetScriptCountEB()'(overrides?: Overrides): Promise<ContractTransaction>

        seedToPrintId(arg0: BigNumberish, overrides?: CallOverrides): Promise<[BigNumber]>

        'seedToPrintId(uint256)'(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<[BigNumber]>

        setBurnEnabled(_enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

        'setBurnEnabled(bool)'(
            _enabled: boolean,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        setEnabledEB(enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

        'setEnabledEB(bool)'(enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

        setLockedEB(locked: boolean, overrides?: Overrides): Promise<ContractTransaction>

        'setLockedEB(bool)'(locked: boolean, overrides?: Overrides): Promise<ContractTransaction>

        setPrintEnabled(_enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

        'setPrintEnabled(bool)'(
            _enabled: boolean,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        setURIEB(newuri: string, overrides?: Overrides): Promise<ContractTransaction>

        'setURIEB(string)'(newuri: string, overrides?: Overrides): Promise<ContractTransaction>

        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<[boolean]>

        'supportsInterface(bytes4)'(
            interfaceId: BytesLike,
            overrides?: CallOverrides
        ): Promise<[boolean]>

        transferOwnership(newOwner: string, overrides?: Overrides): Promise<ContractTransaction>

        'transferOwnership(address)'(
            newOwner: string,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        transferOwnershipEB(newowner: string, overrides?: Overrides): Promise<ContractTransaction>

        'transferOwnershipEB(address)'(
            newowner: string,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        updateScriptEB(
            _script: string,
            index: BigNumberish,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        'updateScriptEB(string,uint256)'(
            _script: string,
            index: BigNumberish,
            overrides?: Overrides
        ): Promise<ContractTransaction>

        withdraw(overrides?: Overrides): Promise<ContractTransaction>

        'withdraw()'(overrides?: Overrides): Promise<ContractTransaction>

        withdrawEB(overrides?: Overrides): Promise<ContractTransaction>

        'withdrawEB()'(overrides?: Overrides): Promise<ContractTransaction>
    }

    EulerBeats(overrides?: CallOverrides): Promise<string>

    'EulerBeats()'(overrides?: CallOverrides): Promise<string>

    addScriptEB(_script: string, overrides?: Overrides): Promise<ContractTransaction>

    'addScriptEB(string)'(_script: string, overrides?: Overrides): Promise<ContractTransaction>

    burnEnabled(overrides?: CallOverrides): Promise<boolean>

    'burnEnabled()'(overrides?: CallOverrides): Promise<boolean>

    burnPrint(
        seed: BigNumberish,
        minimumSupply: BigNumberish,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    'burnPrint(uint256,uint256)'(
        seed: BigNumberish,
        minimumSupply: BigNumberish,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    ensureEulerBeatsSeedOwner(
        seed: BigNumberish,
        _owner: string,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    'ensureEulerBeatsSeedOwner(uint256,address)'(
        seed: BigNumberish,
        _owner: string,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    getSeedIds(
        overrides?: CallOverrides
    ): Promise<
        [
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber
        ]
    >

    'getSeedIds()'(
        overrides?: CallOverrides
    ): Promise<
        [
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber,
            BigNumber
        ]
    >

    mintPrint(
        seed: BigNumberish,
        _owner: string,
        overrides?: PayableOverrides
    ): Promise<ContractTransaction>

    'mintPrint(uint256,address)'(
        seed: BigNumberish,
        _owner: string,
        overrides?: PayableOverrides
    ): Promise<ContractTransaction>

    onERC1155BatchReceived(
        arg0: string,
        arg1: string,
        arg2: BigNumberish[],
        arg3: BigNumberish[],
        arg4: BytesLike,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    'onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)'(
        arg0: string,
        arg1: string,
        arg2: BigNumberish[],
        arg3: BigNumberish[],
        arg4: BytesLike,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    onERC1155Received(
        arg0: string,
        arg1: string,
        arg2: BigNumberish,
        arg3: BigNumberish,
        arg4: BytesLike,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    'onERC1155Received(address,address,uint256,uint256,bytes)'(
        arg0: string,
        arg1: string,
        arg2: BigNumberish,
        arg3: BigNumberish,
        arg4: BytesLike,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    owner(overrides?: CallOverrides): Promise<string>

    'owner()'(overrides?: CallOverrides): Promise<string>

    printEnabled(overrides?: CallOverrides): Promise<boolean>

    'printEnabled()'(overrides?: CallOverrides): Promise<boolean>

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>

    'renounceOwnership()'(overrides?: Overrides): Promise<ContractTransaction>

    resetScriptCountEB(overrides?: Overrides): Promise<ContractTransaction>

    'resetScriptCountEB()'(overrides?: Overrides): Promise<ContractTransaction>

    seedToPrintId(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    'seedToPrintId(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

    setBurnEnabled(_enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

    'setBurnEnabled(bool)'(_enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

    setEnabledEB(enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

    'setEnabledEB(bool)'(enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

    setLockedEB(locked: boolean, overrides?: Overrides): Promise<ContractTransaction>

    'setLockedEB(bool)'(locked: boolean, overrides?: Overrides): Promise<ContractTransaction>

    setPrintEnabled(_enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

    'setPrintEnabled(bool)'(_enabled: boolean, overrides?: Overrides): Promise<ContractTransaction>

    setURIEB(newuri: string, overrides?: Overrides): Promise<ContractTransaction>

    'setURIEB(string)'(newuri: string, overrides?: Overrides): Promise<ContractTransaction>

    supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

    'supportsInterface(bytes4)'(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

    transferOwnership(newOwner: string, overrides?: Overrides): Promise<ContractTransaction>

    'transferOwnership(address)'(
        newOwner: string,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    transferOwnershipEB(newowner: string, overrides?: Overrides): Promise<ContractTransaction>

    'transferOwnershipEB(address)'(
        newowner: string,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    updateScriptEB(
        _script: string,
        index: BigNumberish,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    'updateScriptEB(string,uint256)'(
        _script: string,
        index: BigNumberish,
        overrides?: Overrides
    ): Promise<ContractTransaction>

    withdraw(overrides?: Overrides): Promise<ContractTransaction>

    'withdraw()'(overrides?: Overrides): Promise<ContractTransaction>

    withdrawEB(overrides?: Overrides): Promise<ContractTransaction>

    'withdrawEB()'(overrides?: Overrides): Promise<ContractTransaction>

    callStatic: {
        EulerBeats(overrides?: CallOverrides): Promise<string>

        'EulerBeats()'(overrides?: CallOverrides): Promise<string>

        addScriptEB(_script: string, overrides?: CallOverrides): Promise<void>

        'addScriptEB(string)'(_script: string, overrides?: CallOverrides): Promise<void>

        burnEnabled(overrides?: CallOverrides): Promise<boolean>

        'burnEnabled()'(overrides?: CallOverrides): Promise<boolean>

        burnPrint(
            seed: BigNumberish,
            minimumSupply: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>

        'burnPrint(uint256,uint256)'(
            seed: BigNumberish,
            minimumSupply: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>

        ensureEulerBeatsSeedOwner(
            seed: BigNumberish,
            _owner: string,
            overrides?: CallOverrides
        ): Promise<void>

        'ensureEulerBeatsSeedOwner(uint256,address)'(
            seed: BigNumberish,
            _owner: string,
            overrides?: CallOverrides
        ): Promise<void>

        getSeedIds(
            overrides?: CallOverrides
        ): Promise<
            [
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber
            ]
        >

        'getSeedIds()'(
            overrides?: CallOverrides
        ): Promise<
            [
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber,
                BigNumber
            ]
        >

        mintPrint(seed: BigNumberish, _owner: string, overrides?: CallOverrides): Promise<BigNumber>

        'mintPrint(uint256,address)'(
            seed: BigNumberish,
            _owner: string,
            overrides?: CallOverrides
        ): Promise<BigNumber>

        onERC1155BatchReceived(
            arg0: string,
            arg1: string,
            arg2: BigNumberish[],
            arg3: BigNumberish[],
            arg4: BytesLike,
            overrides?: CallOverrides
        ): Promise<string>

        'onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)'(
            arg0: string,
            arg1: string,
            arg2: BigNumberish[],
            arg3: BigNumberish[],
            arg4: BytesLike,
            overrides?: CallOverrides
        ): Promise<string>

        onERC1155Received(
            arg0: string,
            arg1: string,
            arg2: BigNumberish,
            arg3: BigNumberish,
            arg4: BytesLike,
            overrides?: CallOverrides
        ): Promise<string>

        'onERC1155Received(address,address,uint256,uint256,bytes)'(
            arg0: string,
            arg1: string,
            arg2: BigNumberish,
            arg3: BigNumberish,
            arg4: BytesLike,
            overrides?: CallOverrides
        ): Promise<string>

        owner(overrides?: CallOverrides): Promise<string>

        'owner()'(overrides?: CallOverrides): Promise<string>

        printEnabled(overrides?: CallOverrides): Promise<boolean>

        'printEnabled()'(overrides?: CallOverrides): Promise<boolean>

        renounceOwnership(overrides?: CallOverrides): Promise<void>

        'renounceOwnership()'(overrides?: CallOverrides): Promise<void>

        resetScriptCountEB(overrides?: CallOverrides): Promise<void>

        'resetScriptCountEB()'(overrides?: CallOverrides): Promise<void>

        seedToPrintId(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'seedToPrintId(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        setBurnEnabled(_enabled: boolean, overrides?: CallOverrides): Promise<void>

        'setBurnEnabled(bool)'(_enabled: boolean, overrides?: CallOverrides): Promise<void>

        setEnabledEB(enabled: boolean, overrides?: CallOverrides): Promise<void>

        'setEnabledEB(bool)'(enabled: boolean, overrides?: CallOverrides): Promise<void>

        setLockedEB(locked: boolean, overrides?: CallOverrides): Promise<void>

        'setLockedEB(bool)'(locked: boolean, overrides?: CallOverrides): Promise<void>

        setPrintEnabled(_enabled: boolean, overrides?: CallOverrides): Promise<void>

        'setPrintEnabled(bool)'(_enabled: boolean, overrides?: CallOverrides): Promise<void>

        setURIEB(newuri: string, overrides?: CallOverrides): Promise<void>

        'setURIEB(string)'(newuri: string, overrides?: CallOverrides): Promise<void>

        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<boolean>

        'supportsInterface(bytes4)'(
            interfaceId: BytesLike,
            overrides?: CallOverrides
        ): Promise<boolean>

        transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>

        'transferOwnership(address)'(newOwner: string, overrides?: CallOverrides): Promise<void>

        transferOwnershipEB(newowner: string, overrides?: CallOverrides): Promise<void>

        'transferOwnershipEB(address)'(newowner: string, overrides?: CallOverrides): Promise<void>

        updateScriptEB(
            _script: string,
            index: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>

        'updateScriptEB(string,uint256)'(
            _script: string,
            index: BigNumberish,
            overrides?: CallOverrides
        ): Promise<void>

        withdraw(overrides?: CallOverrides): Promise<void>

        'withdraw()'(overrides?: CallOverrides): Promise<void>

        withdrawEB(overrides?: CallOverrides): Promise<void>

        'withdrawEB()'(overrides?: CallOverrides): Promise<void>
    }

    filters: {
        OwnershipTransferred(
            previousOwner: string | null,
            newOwner: string | null
        ): TypedEventFilter<[string, string], { previousOwner: string; newOwner: string }>
    }

    estimateGas: {
        EulerBeats(overrides?: CallOverrides): Promise<BigNumber>

        'EulerBeats()'(overrides?: CallOverrides): Promise<BigNumber>

        addScriptEB(_script: string, overrides?: Overrides): Promise<BigNumber>

        'addScriptEB(string)'(_script: string, overrides?: Overrides): Promise<BigNumber>

        burnEnabled(overrides?: CallOverrides): Promise<BigNumber>

        'burnEnabled()'(overrides?: CallOverrides): Promise<BigNumber>

        burnPrint(
            seed: BigNumberish,
            minimumSupply: BigNumberish,
            overrides?: Overrides
        ): Promise<BigNumber>

        'burnPrint(uint256,uint256)'(
            seed: BigNumberish,
            minimumSupply: BigNumberish,
            overrides?: Overrides
        ): Promise<BigNumber>

        ensureEulerBeatsSeedOwner(
            seed: BigNumberish,
            _owner: string,
            overrides?: Overrides
        ): Promise<BigNumber>

        'ensureEulerBeatsSeedOwner(uint256,address)'(
            seed: BigNumberish,
            _owner: string,
            overrides?: Overrides
        ): Promise<BigNumber>

        getSeedIds(overrides?: CallOverrides): Promise<BigNumber>

        'getSeedIds()'(overrides?: CallOverrides): Promise<BigNumber>

        mintPrint(
            seed: BigNumberish,
            _owner: string,
            overrides?: PayableOverrides
        ): Promise<BigNumber>

        'mintPrint(uint256,address)'(
            seed: BigNumberish,
            _owner: string,
            overrides?: PayableOverrides
        ): Promise<BigNumber>

        onERC1155BatchReceived(
            arg0: string,
            arg1: string,
            arg2: BigNumberish[],
            arg3: BigNumberish[],
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<BigNumber>

        'onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)'(
            arg0: string,
            arg1: string,
            arg2: BigNumberish[],
            arg3: BigNumberish[],
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<BigNumber>

        onERC1155Received(
            arg0: string,
            arg1: string,
            arg2: BigNumberish,
            arg3: BigNumberish,
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<BigNumber>

        'onERC1155Received(address,address,uint256,uint256,bytes)'(
            arg0: string,
            arg1: string,
            arg2: BigNumberish,
            arg3: BigNumberish,
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<BigNumber>

        owner(overrides?: CallOverrides): Promise<BigNumber>

        'owner()'(overrides?: CallOverrides): Promise<BigNumber>

        printEnabled(overrides?: CallOverrides): Promise<BigNumber>

        'printEnabled()'(overrides?: CallOverrides): Promise<BigNumber>

        renounceOwnership(overrides?: Overrides): Promise<BigNumber>

        'renounceOwnership()'(overrides?: Overrides): Promise<BigNumber>

        resetScriptCountEB(overrides?: Overrides): Promise<BigNumber>

        'resetScriptCountEB()'(overrides?: Overrides): Promise<BigNumber>

        seedToPrintId(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        'seedToPrintId(uint256)'(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>

        setBurnEnabled(_enabled: boolean, overrides?: Overrides): Promise<BigNumber>

        'setBurnEnabled(bool)'(_enabled: boolean, overrides?: Overrides): Promise<BigNumber>

        setEnabledEB(enabled: boolean, overrides?: Overrides): Promise<BigNumber>

        'setEnabledEB(bool)'(enabled: boolean, overrides?: Overrides): Promise<BigNumber>

        setLockedEB(locked: boolean, overrides?: Overrides): Promise<BigNumber>

        'setLockedEB(bool)'(locked: boolean, overrides?: Overrides): Promise<BigNumber>

        setPrintEnabled(_enabled: boolean, overrides?: Overrides): Promise<BigNumber>

        'setPrintEnabled(bool)'(_enabled: boolean, overrides?: Overrides): Promise<BigNumber>

        setURIEB(newuri: string, overrides?: Overrides): Promise<BigNumber>

        'setURIEB(string)'(newuri: string, overrides?: Overrides): Promise<BigNumber>

        supportsInterface(interfaceId: BytesLike, overrides?: CallOverrides): Promise<BigNumber>

        'supportsInterface(bytes4)'(
            interfaceId: BytesLike,
            overrides?: CallOverrides
        ): Promise<BigNumber>

        transferOwnership(newOwner: string, overrides?: Overrides): Promise<BigNumber>

        'transferOwnership(address)'(newOwner: string, overrides?: Overrides): Promise<BigNumber>

        transferOwnershipEB(newowner: string, overrides?: Overrides): Promise<BigNumber>

        'transferOwnershipEB(address)'(newowner: string, overrides?: Overrides): Promise<BigNumber>

        updateScriptEB(
            _script: string,
            index: BigNumberish,
            overrides?: Overrides
        ): Promise<BigNumber>

        'updateScriptEB(string,uint256)'(
            _script: string,
            index: BigNumberish,
            overrides?: Overrides
        ): Promise<BigNumber>

        withdraw(overrides?: Overrides): Promise<BigNumber>

        'withdraw()'(overrides?: Overrides): Promise<BigNumber>

        withdrawEB(overrides?: Overrides): Promise<BigNumber>

        'withdrawEB()'(overrides?: Overrides): Promise<BigNumber>
    }

    populateTransaction: {
        EulerBeats(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'EulerBeats()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        addScriptEB(_script: string, overrides?: Overrides): Promise<PopulatedTransaction>

        'addScriptEB(string)'(_script: string, overrides?: Overrides): Promise<PopulatedTransaction>

        burnEnabled(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'burnEnabled()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        burnPrint(
            seed: BigNumberish,
            minimumSupply: BigNumberish,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        'burnPrint(uint256,uint256)'(
            seed: BigNumberish,
            minimumSupply: BigNumberish,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        ensureEulerBeatsSeedOwner(
            seed: BigNumberish,
            _owner: string,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        'ensureEulerBeatsSeedOwner(uint256,address)'(
            seed: BigNumberish,
            _owner: string,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        getSeedIds(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'getSeedIds()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        mintPrint(
            seed: BigNumberish,
            _owner: string,
            overrides?: PayableOverrides
        ): Promise<PopulatedTransaction>

        'mintPrint(uint256,address)'(
            seed: BigNumberish,
            _owner: string,
            overrides?: PayableOverrides
        ): Promise<PopulatedTransaction>

        onERC1155BatchReceived(
            arg0: string,
            arg1: string,
            arg2: BigNumberish[],
            arg3: BigNumberish[],
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        'onERC1155BatchReceived(address,address,uint256[],uint256[],bytes)'(
            arg0: string,
            arg1: string,
            arg2: BigNumberish[],
            arg3: BigNumberish[],
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        onERC1155Received(
            arg0: string,
            arg1: string,
            arg2: BigNumberish,
            arg3: BigNumberish,
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        'onERC1155Received(address,address,uint256,uint256,bytes)'(
            arg0: string,
            arg1: string,
            arg2: BigNumberish,
            arg3: BigNumberish,
            arg4: BytesLike,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'owner()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        printEnabled(overrides?: CallOverrides): Promise<PopulatedTransaction>

        'printEnabled()'(overrides?: CallOverrides): Promise<PopulatedTransaction>

        renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>

        'renounceOwnership()'(overrides?: Overrides): Promise<PopulatedTransaction>

        resetScriptCountEB(overrides?: Overrides): Promise<PopulatedTransaction>

        'resetScriptCountEB()'(overrides?: Overrides): Promise<PopulatedTransaction>

        seedToPrintId(arg0: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>

        'seedToPrintId(uint256)'(
            arg0: BigNumberish,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        setBurnEnabled(_enabled: boolean, overrides?: Overrides): Promise<PopulatedTransaction>

        'setBurnEnabled(bool)'(
            _enabled: boolean,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        setEnabledEB(enabled: boolean, overrides?: Overrides): Promise<PopulatedTransaction>

        'setEnabledEB(bool)'(enabled: boolean, overrides?: Overrides): Promise<PopulatedTransaction>

        setLockedEB(locked: boolean, overrides?: Overrides): Promise<PopulatedTransaction>

        'setLockedEB(bool)'(locked: boolean, overrides?: Overrides): Promise<PopulatedTransaction>

        setPrintEnabled(_enabled: boolean, overrides?: Overrides): Promise<PopulatedTransaction>

        'setPrintEnabled(bool)'(
            _enabled: boolean,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        setURIEB(newuri: string, overrides?: Overrides): Promise<PopulatedTransaction>

        'setURIEB(string)'(newuri: string, overrides?: Overrides): Promise<PopulatedTransaction>

        supportsInterface(
            interfaceId: BytesLike,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        'supportsInterface(bytes4)'(
            interfaceId: BytesLike,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        transferOwnership(newOwner: string, overrides?: Overrides): Promise<PopulatedTransaction>

        'transferOwnership(address)'(
            newOwner: string,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        transferOwnershipEB(newowner: string, overrides?: Overrides): Promise<PopulatedTransaction>

        'transferOwnershipEB(address)'(
            newowner: string,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        updateScriptEB(
            _script: string,
            index: BigNumberish,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        'updateScriptEB(string,uint256)'(
            _script: string,
            index: BigNumberish,
            overrides?: Overrides
        ): Promise<PopulatedTransaction>

        withdraw(overrides?: Overrides): Promise<PopulatedTransaction>

        'withdraw()'(overrides?: Overrides): Promise<PopulatedTransaction>

        withdrawEB(overrides?: Overrides): Promise<PopulatedTransaction>

        'withdrawEB()'(overrides?: Overrides): Promise<PopulatedTransaction>
    }
}
